apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: dlq-event-received
spec:
  template:
    container:
      env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://alloy-metrics-traces.observability.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "dlq-event-received-eventsource"
