apiVersion: v1
kind: Service
metadata:
  name: dlq-event-received-eventsource-svc
  namespace: bookinfo
spec:
  selector:
    eventsource-name: dlq-event-received
  ports:
    - port: 12004
      targetPort: 12004
