apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: book-added-sensor
spec:
  template:
    container:
      env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://alloy-metrics-traces.observability.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "book-added-sensor"
  triggers:
    - template:
        name: create-detail
        http:
          url: http://details-write.bookinfo.svc.cluster.local/v1/details
          method: POST
          headers:
            Content-Type: application/json
          payload:
            - src:
                dependencyName: book-added-dep
                dataKey: body
              dest: ""
      retryStrategy:
        steps: 3
        duration: 2s
    - template:
        name: notify-book-added
        http:
          url: http://notification.bookinfo.svc.cluster.local/v1/notifications
          method: POST
          headers:
            Content-Type: application/json
          payload:
            - src:
                dependencyName: book-added-dep
                dataKey: body.title
              dest: subject
            - src:
                dependencyName: book-added-dep
                value: "New book added"
              dest: body
            - src:
                dependencyName: book-added-dep
                value: "system@bookinfo"
              dest: recipient
            - src:
                dependencyName: book-added-dep
                value: "email"
              dest: channel
      retryStrategy:
        steps: 3
        duration: 2s
