version: 2
project_name: notification

builds:
  - id: notification
    binary: notification
    main: ./services/notification/cmd/
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w

archives:
  - id: notification
    builds:
      - notification
    name_template: "notification_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format: tar.gz

dockers:
  - id: notification-amd64
    ids:
      - notification
    image_templates:
      - "ghcr.io/kaio6fellipe/event-driven-bookinfo/notification:{{ .Tag }}-amd64"
    dockerfile: build/Dockerfile.notification
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=notification"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

  - id: notification-arm64
    ids:
      - notification
    image_templates:
      - "ghcr.io/kaio6fellipe/event-driven-bookinfo/notification:{{ .Tag }}-arm64"
    dockerfile: build/Dockerfile.notification
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.title=notification"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"

docker_manifests:
  - name_template: "ghcr.io/kaio6fellipe/event-driven-bookinfo/notification:{{ .Tag }}"
    image_templates:
      - "ghcr.io/kaio6fellipe/event-driven-bookinfo/notification:{{ .Tag }}-amd64"
      - "ghcr.io/kaio6fellipe/event-driven-bookinfo/notification:{{ .Tag }}-arm64"

release:
  disable: true

changelog:
  use: github
