FROM golang:1.25-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY pkg/ ./pkg/
COPY services/notification/ ./services/notification/
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o /bin/notification ./services/notification/cmd/

FROM scratch
COPY --from=builder /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=builder /bin/notification /bin/notification
USER 65534:65534
ENTRYPOINT ["/bin/notification"]
