apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: dlq-event-received
spec:
  eventBusName: kafka
  webhook:
    dlq-event-received:
      port: "12004"
      endpoint: /dlq-event-received
      method: POST
