apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: dlq-event-received-sensor
spec:
  eventBusName: kafka
  dependencies:
    - name: dlq-event-received-dep
      eventSourceName: dlq-event-received
      eventName: dlq-event-received
  triggers:
    - template:
        name: ingest-dlq-event
        http:
          url: http://dlqueue/v1/events
          method: POST
          headers:
            Content-Type: application/json
          payload:
            - src:
                dependencyName: dlq-event-received-dep
                dataKey: body
              dest: ""
      atLeastOnce: true
      retryStrategy:
        steps: 5
        duration: 2s
        factor: 2.0
        jitter: 1
