# deploy/notification/values-local.yaml
serviceName: notification
fullnameOverride: notification
image:
  repository: event-driven-bookinfo/notification
  tag: local

postgresql:
  enabled: true
  auth:
    database: "bookinfo_notification"

config:
  LOG_LEVEL: "debug"

observability:
  otelEndpoint: "http://alloy-metrics-traces.observability.svc.cluster.local:4317"
  pyroscopeAddress: "http://pyroscope.observability.svc.cluster.local:4040"
