apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init
  namespace: bookinfo
data:
  init.sql: |
    CREATE DATABASE bookinfo_ratings;
    CREATE DATABASE bookinfo_details;
    CREATE DATABASE bookinfo_reviews;
    CREATE DATABASE bookinfo_notification;
    CREATE DATABASE bookinfo_dlqueue;
