# Bitnami Redis - standalone mode for local k8s development
architecture: standalone

auth:
  enabled: false

master:
  persistence:
    enabled: true
    size: 1Gi

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 128Mi
