# deploy/ratings/values-local.yaml
serviceName: ratings
fullnameOverride: ratings
image:
  repository: event-driven-bookinfo/ratings
  tag: local

postgresql:
  enabled: true
  auth:
    database: "bookinfo_ratings"

config:
  LOG_LEVEL: "debug"
  KAFKA_BROKERS: "bookinfo-kafka-kafka-bootstrap.platform.svc.cluster.local:9092"
  KAFKA_TOPIC: "bookinfo_ratings_events"

observability:
  otelEndpoint: "http://alloy-metrics-traces.observability.svc.cluster.local:4317"
  pyroscopeAddress: "http://pyroscope.observability.svc.cluster.local:4040"

events:
  kafka:
    broker: "bookinfo-kafka-kafka-bootstrap.platform.svc.cluster.local:9092"
  exposed:
    events:
      topic: bookinfo_ratings_events
      eventBusName: kafka

cqrs:
  enabled: true
  read:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
  write:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
  endpoints:
    rating-submitted:
      port: 12002
      triggers:
        - name: create-rating
          url: self
          payload:
            - passthrough

sensor:
  dlq:
    url: "http://dlq-event-received-eventsource-svc.bookinfo.svc.cluster.local:12004/v1/events"

gateway:
  name: default-gw
  namespace: platform
  sectionName: web
