# deploy/dlqueue/values-local.yaml
serviceName: dlqueue
fullnameOverride: dlqueue
image:
  repository: event-driven-bookinfo/dlqueue
  tag: local

postgresql:
  enabled: true
  auth:
    database: "bookinfo_dlqueue"

config:
  LOG_LEVEL: "debug"

observability:
  otelEndpoint: "http://alloy-metrics-traces.observability.svc.cluster.local:4317"
  pyroscopeAddress: "http://pyroscope.observability.svc.cluster.local:4040"

sensor:
  dlq:
    enabled: false

cqrs:
  enabled: true
  read:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
  write:
    replicas: 1
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
gateway:
  name: default-gw
  namespace: platform
  sectionName: web
