apiVersion: v1
kind: Service
metadata:
  name: review-deleted-eventsource-svc
  namespace: bookinfo
spec:
  selector:
    eventsource-name: review-deleted
  ports:
    - port: 12003
      targetPort: 12003
