apiVersion: v1
kind: Service
metadata:
  name: review-submitted-eventsource-svc
  namespace: bookinfo
spec:
  selector:
    eventsource-name: review-submitted
  ports:
    - port: 12001
      targetPort: 12001
