apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: review-submitted
spec:
  template:
    container:
      env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://alloy-metrics-traces.observability.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "review-submitted-eventsource"
  webhook:
    review-submitted:
      endpoint: /v1/reviews
