apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo

resources:
  - ../../base
  - deployment-write.yaml
  - service-write.yaml
  - eventsource-service.yaml
  - eventsource-delete-service.yaml

patches:
  - path: deployment-read-patch.yaml
    target:
      kind: Deployment
      name: reviews
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: reviews
  - path: eventsource-patch.yaml
    target:
      kind: EventSource
      name: review-submitted
  - path: eventsource-delete-patch.yaml
    target:
      kind: EventSource
      name: review-deleted
  - path: sensor-patch.yaml
    target:
      kind: Sensor
      name: review-submitted-sensor

images:
  - name: event-driven-bookinfo/reviews
    newTag: local
