apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: review-submitted-sensor
spec:
  template:
    container:
      env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://alloy-metrics-traces.observability.svc.cluster.local:4317"
        - name: OTEL_SERVICE_NAME
          value: "review-submitted-sensor"
  triggers:
    - template:
        name: create-review
        conditions: review-submitted-dep
        http:
          url: http://reviews-write.bookinfo.svc.cluster.local/v1/reviews
          method: POST
          headers:
            Content-Type: application/json
          payload:
            - src:
                dependencyName: review-submitted-dep
                dataKey: body
              dest: ""
      atLeastOnce: true
      retryStrategy:
        steps: 3
        duration: 2s
        factor: 2.0
        jitter: 1
      dlqTrigger:
        template:
          name: dlq-create-review
          http:
            url: http://dlq-event-received-eventsource-svc.bookinfo.svc.cluster.local:12004/dlq-event-received
            method: POST
            headers:
              Content-Type: application/json
            payload:
              - src:
                  dependencyName: review-submitted-dep
                  dataKey: body
                dest: original_payload
              - src:
                  dependencyName: review-submitted-dep
                  contextKey: id
                dest: event_id
              - src:
                  dependencyName: review-submitted-dep
                  contextKey: type
                dest: event_type
              - src:
                  dependencyName: review-submitted-dep
                  contextKey: source
                dest: event_source
              - src:
                  dependencyName: review-submitted-dep
                  contextKey: subject
                dest: event_subject
              - src:
                  dependencyName: review-submitted-dep
                  contextKey: time
                dest: event_timestamp
              - src:
                  dependencyName: review-submitted-dep
                  contextKey: datacontenttype
                dest: datacontenttype
              - src:
                  dependencyName: review-submitted-dep
                  dataKey: header
                dest: original_headers
              - src:
                  dependencyName: review-submitted-dep
                  value: "review-submitted-sensor"
                dest: sensor_name
              - src:
                  dependencyName: review-submitted-dep
                  value: "create-review"
                dest: failed_trigger
              - src:
                  dependencyName: review-submitted-dep
                  value: "http://review-submitted-eventsource-svc.bookinfo.svc.cluster.local:12001/review-submitted"
                dest: eventsource_url
              - src:
                  dependencyName: review-submitted-dep
                  value: "bookinfo"
                dest: namespace
        atLeastOnce: true
        retryStrategy:
          steps: 5
          duration: 2s
          factor: 2.0
          jitter: 1
    - template:
        name: notify-review-submitted
        conditions: review-submitted-dep
        http:
          url: http://notification.bookinfo.svc.cluster.local/v1/notifications
          method: POST
          headers:
            Content-Type: application/json
          payload:
            - src:
                dependencyName: review-submitted-dep
                dataKey: body.product_id
              dest: subject
            - src:
                dependencyName: review-submitted-dep
                value: "New review submitted"
              dest: body
            - src:
                dependencyName: review-submitted-dep
                value: "system@bookinfo"
              dest: recipient
            - src:
                dependencyName: review-submitted-dep
                value: "email"
              dest: channel
      atLeastOnce: true
      retryStrategy:
        steps: 3
        duration: 2s
        factor: 2.0
        jitter: 1
      dlqTrigger:
        template:
          name: dlq-notify-review-submitted
          http:
            url: http://dlq-event-received-eventsource-svc.bookinfo.svc.cluster.local:12004/dlq-event-received
            method: POST
            headers:
              Content-Type: application/json
            payload:
              - src:
                  dependencyName: review-submitted-dep
                  dataKey: body
                dest: original_payload
              - src:
                  dependencyName: review-submitted-dep
                  contextKey: id
                dest: event_id
              - src:
                  dependencyName: review-submitted-dep
                  contextKey: type
                dest: event_type
              - src:
                  dependencyName: review-submitted-dep
                  contextKey: source
                dest: event_source
              - src:
                  dependencyName: review-submitted-dep
                  contextKey: subject
                dest: event_subject
              - src:
                  dependencyName: review-submitted-dep
                  contextKey: time
                dest: event_timestamp
              - src:
                  dependencyName: review-submitted-dep
                  contextKey: datacontenttype
                dest: datacontenttype
              - src:
                  dependencyName: review-submitted-dep
                  dataKey: header
                dest: original_headers
              - src:
                  dependencyName: review-submitted-dep
                  value: "review-submitted-sensor"
                dest: sensor_name
              - src:
                  dependencyName: review-submitted-dep
                  value: "notify-review-submitted"
                dest: failed_trigger
              - src:
                  dependencyName: review-submitted-dep
                  value: "http://review-submitted-eventsource-svc.bookinfo.svc.cluster.local:12001/review-submitted"
                dest: eventsource_url
              - src:
                  dependencyName: review-submitted-dep
                  value: "bookinfo"
                dest: namespace
        atLeastOnce: true
        retryStrategy:
          steps: 5
          duration: 2s
          factor: 2.0
          jitter: 1
    - template:
        name: delete-review-write
        conditions: review-deleted-dep
        http:
          url: http://reviews-write.bookinfo.svc.cluster.local/v1/reviews/delete
          method: POST
          headers:
            Content-Type: application/json
          payload:
            - src:
                dependencyName: review-deleted-dep
                dataKey: body.review_id
              dest: review_id
      atLeastOnce: true
      retryStrategy:
        steps: 3
        duration: 2s
        factor: 2.0
        jitter: 1
      dlqTrigger:
        template:
          name: dlq-delete-review-write
          http:
            url: http://dlq-event-received-eventsource-svc.bookinfo.svc.cluster.local:12004/dlq-event-received
            method: POST
            headers:
              Content-Type: application/json
            payload:
              - src:
                  dependencyName: review-deleted-dep
                  dataKey: body
                dest: original_payload
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: id
                dest: event_id
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: type
                dest: event_type
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: source
                dest: event_source
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: subject
                dest: event_subject
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: time
                dest: event_timestamp
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: datacontenttype
                dest: datacontenttype
              - src:
                  dependencyName: review-deleted-dep
                  dataKey: header
                dest: original_headers
              - src:
                  dependencyName: review-deleted-dep
                  value: "review-submitted-sensor"
                dest: sensor_name
              - src:
                  dependencyName: review-deleted-dep
                  value: "delete-review-write"
                dest: failed_trigger
              - src:
                  dependencyName: review-deleted-dep
                  value: "http://review-deleted-eventsource-svc.bookinfo.svc.cluster.local:12003/review-deleted"
                dest: eventsource_url
              - src:
                  dependencyName: review-deleted-dep
                  value: "bookinfo"
                dest: namespace
        atLeastOnce: true
        retryStrategy:
          steps: 5
          duration: 2s
          factor: 2.0
          jitter: 1
    - template:
        name: delete-review-read
        conditions: review-deleted-dep
        http:
          url: http://reviews.bookinfo.svc.cluster.local/v1/reviews/delete
          method: POST
          headers:
            Content-Type: application/json
          payload:
            - src:
                dependencyName: review-deleted-dep
                dataKey: body.review_id
              dest: review_id
      atLeastOnce: true
      retryStrategy:
        steps: 3
        duration: 2s
        factor: 2.0
        jitter: 1
      dlqTrigger:
        template:
          name: dlq-delete-review-read
          http:
            url: http://dlq-event-received-eventsource-svc.bookinfo.svc.cluster.local:12004/dlq-event-received
            method: POST
            headers:
              Content-Type: application/json
            payload:
              - src:
                  dependencyName: review-deleted-dep
                  dataKey: body
                dest: original_payload
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: id
                dest: event_id
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: type
                dest: event_type
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: source
                dest: event_source
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: subject
                dest: event_subject
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: time
                dest: event_timestamp
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: datacontenttype
                dest: datacontenttype
              - src:
                  dependencyName: review-deleted-dep
                  dataKey: header
                dest: original_headers
              - src:
                  dependencyName: review-deleted-dep
                  value: "review-submitted-sensor"
                dest: sensor_name
              - src:
                  dependencyName: review-deleted-dep
                  value: "delete-review-read"
                dest: failed_trigger
              - src:
                  dependencyName: review-deleted-dep
                  value: "http://review-deleted-eventsource-svc.bookinfo.svc.cluster.local:12003/review-deleted"
                dest: eventsource_url
              - src:
                  dependencyName: review-deleted-dep
                  value: "bookinfo"
                dest: namespace
        atLeastOnce: true
        retryStrategy:
          steps: 5
          duration: 2s
          factor: 2.0
          jitter: 1
    - template:
        name: notify-review-deleted
        conditions: review-deleted-dep
        http:
          url: http://notification.bookinfo.svc.cluster.local/v1/notifications
          method: POST
          headers:
            Content-Type: application/json
          payload:
            - src:
                dependencyName: review-deleted-dep
                dataKey: body.review_id
              dest: subject
            - src:
                dependencyName: review-deleted-dep
                value: "Review deleted"
              dest: body
            - src:
                dependencyName: review-deleted-dep
                value: "system@bookinfo"
              dest: recipient
            - src:
                dependencyName: review-deleted-dep
                value: "email"
              dest: channel
      atLeastOnce: true
      retryStrategy:
        steps: 3
        duration: 2s
        factor: 2.0
        jitter: 1
      dlqTrigger:
        template:
          name: dlq-notify-review-deleted
          http:
            url: http://dlq-event-received-eventsource-svc.bookinfo.svc.cluster.local:12004/dlq-event-received
            method: POST
            headers:
              Content-Type: application/json
            payload:
              - src:
                  dependencyName: review-deleted-dep
                  dataKey: body
                dest: original_payload
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: id
                dest: event_id
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: type
                dest: event_type
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: source
                dest: event_source
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: subject
                dest: event_subject
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: time
                dest: event_timestamp
              - src:
                  dependencyName: review-deleted-dep
                  contextKey: datacontenttype
                dest: datacontenttype
              - src:
                  dependencyName: review-deleted-dep
                  dataKey: header
                dest: original_headers
              - src:
                  dependencyName: review-deleted-dep
                  value: "review-submitted-sensor"
                dest: sensor_name
              - src:
                  dependencyName: review-deleted-dep
                  value: "notify-review-deleted"
                dest: failed_trigger
              - src:
                  dependencyName: review-deleted-dep
                  value: "http://review-deleted-eventsource-svc.bookinfo.svc.cluster.local:12003/review-deleted"
                dest: eventsource_url
              - src:
                  dependencyName: review-deleted-dep
                  value: "bookinfo"
                dest: namespace
        atLeastOnce: true
        retryStrategy:
          steps: 5
          duration: 2s
          factor: 2.0
          jitter: 1
