apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: rating-submitted-sensor
spec:
  eventBusName: kafka
  dependencies:
    - name: rating-submitted-dep
      eventSourceName: rating-submitted
      eventName: rating-submitted
  triggers:
    - template:
        name: create-rating
        http:
          url: http://ratings/v1/ratings
          method: POST
          headers:
            Content-Type: application/json
          payload:
            - src:
                dependencyName: rating-submitted-dep
                dataKey: body
              dest: ""
      retryStrategy:
        steps: 3
        duration: 2s
    - template:
        name: notify-rating-submitted
        http:
          url: http://notification/v1/notifications
          method: POST
          headers:
            Content-Type: application/json
          payload:
            - src:
                dependencyName: rating-submitted-dep
                dataKey: body.product_id
              dest: subject
            - src:
                dependencyName: rating-submitted-dep
                value: "New rating submitted"
              dest: body
            - src:
                dependencyName: rating-submitted-dep
                value: "system@bookinfo"
              dest: recipient
            - src:
                dependencyName: rating-submitted-dep
                value: "email"
              dest: channel
      retryStrategy:
        steps: 3
        duration: 2s
