// Package values emits deploy/<svc>/values-generated.yaml — the
// disjoint subset of cqrs.endpoints and events.exposed that specgen owns.
//
// It owns only the keys derived from spec:
//   - cqrs.endpoints.<EventName>.{method, endpoint} for POST endpoints with an EventName
//   - events.exposed.<ExposureKey>.{contentType, eventTypes} for Exposed descriptors
//
// Everything else (port, topic, broker, replica count) stays in the
// hand-edited values-local.yaml, which is deep-merged with this file at
// helm install time.
package values

import (
	"bytes"
	"fmt"
	"sort"

	"gopkg.in/yaml.v3"

	"github.com/kaio6fellipe/event-driven-bookinfo/tools/specgen/internal/walker"
	"github.com/kaio6fellipe/event-driven-bookinfo/tools/specgen/internal/yamlutil"
)

// Input holds everything Build needs to produce a values-generated.yaml.
type Input struct {
	ServiceName string
	Endpoints   []walker.EndpointInfo
	Exposed     []walker.DescriptorInfo
}

// Build returns the YAML bytes of the values-generated.yaml document.
//
// cqrs.endpoints is omitted entirely when no Endpoint has an EventName.
// events.exposed is omitted entirely when Exposed is empty.
//
// Multi-descriptor grouping: descriptors sharing an ExposureKey are merged
// into one entry. ContentType is taken from the first descriptor in the group
// (sorted by Name); if descriptors in the same group have differing
// ContentTypes, the first one wins — this situation is unusual in practice.
func Build(in Input) ([]byte, error) {
	docNode := yamlutil.Mapping()

	// --- cqrs.endpoints block ---
	// Include only endpoints that have a non-empty EventName.
	type cqrsEntry struct {
		eventName string
		method    string
		path      string
	}
	var cqrsEntries []cqrsEntry
	for _, ep := range in.Endpoints {
		if ep.EventName == "" {
			continue
		}
		cqrsEntries = append(cqrsEntries, cqrsEntry{
			eventName: ep.EventName,
			method:    ep.Method,
			path:      ep.Path,
		})
	}
	// Sort alphabetically by eventName for determinism.
	sort.Slice(cqrsEntries, func(i, j int) bool {
		return cqrsEntries[i].eventName < cqrsEntries[j].eventName
	})

	if len(cqrsEntries) > 0 {
		endpointsNode := yamlutil.Mapping()
		for _, e := range cqrsEntries {
			entryNode := yamlutil.Mapping()
			yamlutil.AddScalar(entryNode, "method", e.method)
			yamlutil.AddScalar(entryNode, "endpoint", e.path)
			yamlutil.AddMapping(endpointsNode, e.eventName, entryNode)
		}
		cqrsNode := yamlutil.Mapping()
		yamlutil.AddMapping(cqrsNode, "endpoints", endpointsNode)
		yamlutil.AddMapping(docNode, "cqrs", cqrsNode)
	}

	// --- events.exposed block ---
	// Group descriptors by ExposureKey (fall back to Name when ExposureKey is empty).
	type exposedGroup struct {
		contentType string   // ContentType of the first descriptor (sorted by Name)
		ceTypes     []string // Union of all CETypes in the group, sorted alphabetically
	}
	groupMap := map[string]*exposedGroup{}
	groupOrder := []string{}

	for _, d := range in.Exposed {
		key := d.ExposureKey
		if key == "" {
			key = d.Name
		}
		g, exists := groupMap[key]
		if !exists {
			g = &exposedGroup{}
			groupMap[key] = g
			groupOrder = append(groupOrder, key)
		}
		g.ceTypes = append(g.ceTypes, d.CEType)
	}

	// For each group, sort descriptors by Name so ContentType is deterministic
	// (first by Name order), and sort CETypes alphabetically.
	//
	// We derive ContentType from the first descriptor in Name order. Because
	// we only stored CETypes above, we need a second pass over in.Exposed.
	for key, g := range groupMap {
		// Collect all descriptors for this group, sorted by Name.
		var descs []walker.DescriptorInfo
		for _, d := range in.Exposed {
			dk := d.ExposureKey
			if dk == "" {
				dk = d.Name
			}
			if dk == key {
				descs = append(descs, d)
			}
		}
		sort.Slice(descs, func(i, j int) bool {
			return descs[i].Name < descs[j].Name
		})
		if len(descs) > 0 {
			g.contentType = descs[0].ContentType
		}
		sort.Strings(g.ceTypes)
		_ = g // already in groupMap
	}

	// Sort group keys alphabetically for determinism.
	sort.Strings(groupOrder)

	if len(groupOrder) > 0 {
		exposedNode := yamlutil.Mapping()
		for _, key := range groupOrder {
			g := groupMap[key]

			entryNode := yamlutil.Mapping()
			yamlutil.AddScalar(entryNode, "contentType", g.contentType)

			seqNode := &yaml.Node{Kind: yaml.SequenceNode, Tag: "!!seq"}
			for _, ct := range g.ceTypes {
				seqNode.Content = append(seqNode.Content,
					&yaml.Node{Kind: yaml.ScalarNode, Tag: "!!str", Value: ct},
				)
			}
			yamlutil.AddMapping(entryNode, "eventTypes", seqNode)
			yamlutil.AddMapping(exposedNode, key, entryNode)
		}
		eventsNode := yamlutil.Mapping()
		yamlutil.AddMapping(eventsNode, "exposed", exposedNode)
		yamlutil.AddMapping(docNode, "events", eventsNode)
	}

	root := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{docNode}}

	var buf bytes.Buffer
	buf.WriteString("# DO NOT EDIT — generated by tools/specgen from\n")
	if len(in.Endpoints) > 0 {
		buf.WriteString("#   services/" + in.ServiceName + "/internal/adapter/inbound/http/endpoints.go\n")
	}
	if len(in.Exposed) > 0 {
		buf.WriteString("#   services/" + in.ServiceName + "/internal/adapter/outbound/kafka/exposed.go\n")
	}
	buf.WriteString("# Run `make generate-specs` to refresh.\n")

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)
	if err := enc.Encode(root); err != nil {
		return nil, fmt.Errorf("encoding YAML: %w", err)
	}
	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("closing YAML encoder: %w", err)
	}
	return buf.Bytes(), nil
}
