# Strimzi Kafka Operator - local dev values
# Chart: strimzi/strimzi-kafka-operator
replicas: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

watchAnyNamespace: true
