alloy:
  configMap:
    create: false
  clustering:
    enabled: false
  extraPorts:
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
      protocol: TCP
    - name: otlp-http
      port: 4318
      targetPort: 4318
      protocol: TCP

controller:
  type: deployment
  replicas: 1

configMap:
  create: true
  name: alloy-metrics-traces-config
  key: config.alloy

serviceAccount:
  create: true

rbac:
  create: true
