# Headlamp Kubernetes Dashboard
# Helm chart: headlamp/headlamp
# Repo: https://charts.kubernetes-sigs.io/headlamp

service:
  type: NodePort
  port: 80
  nodePort: 30444

clusterRoleBinding:
  create: true
  clusterRoleName: cluster-admin

ingress:
  enabled: false
