// Package backstage emits the per-service catalog-info.yaml that the
// external IDP (Backstage) discovers via its GitHub integration.
package backstage

import (
	"bytes"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/kaio6fellipe/event-driven-bookinfo/tools/specgen/internal/walker"
	"github.com/kaio6fellipe/event-driven-bookinfo/tools/specgen/internal/yamlutil"
)

// Input holds everything Build needs to produce a catalog-info.yaml.
type Input struct {
	ServiceName   string
	Owner         string
	RepoTreeURL   string
	HasOpenAPI    bool
	HasAsyncAPI   bool
	ExposedSubset []walker.DescriptorInfo
	ExposedNames  []string
}

// Build returns the multi-document YAML bytes for a Backstage catalog-info.yaml.
// The output contains up to three documents: Component, OpenAPI API entity, and
// AsyncAPI API entity. Documents are omitted when HasOpenAPI or HasAsyncAPI is false.
func Build(in Input) ([]byte, error) {
	if in.Owner == "" {
		return nil, fmt.Errorf("Owner is required")
	}
	if in.RepoTreeURL == "" {
		return nil, fmt.Errorf("RepoTreeURL is required")
	}

	var buf bytes.Buffer
	buf.WriteString("# DO NOT EDIT — generated by tools/specgen.\n")

	enc := yaml.NewEncoder(&buf)
	enc.SetIndent(2)

	// Component document
	componentNode := buildComponent(in)
	if err := enc.Encode(componentNode); err != nil {
		return nil, fmt.Errorf("encoding Component: %w", err)
	}

	// API: openapi
	if in.HasOpenAPI {
		if err := enc.Encode(buildOpenAPIEntity(in)); err != nil {
			return nil, fmt.Errorf("encoding OpenAPI entity: %w", err)
		}
	}

	// API: asyncapi
	if in.HasAsyncAPI {
		if err := enc.Encode(buildAsyncAPIEntity(in)); err != nil {
			return nil, fmt.Errorf("encoding AsyncAPI entity: %w", err)
		}
	}

	if err := enc.Close(); err != nil {
		return nil, fmt.Errorf("closing encoder: %w", err)
	}
	return buf.Bytes(), nil
}

func buildComponent(in Input) *yaml.Node {
	node := yamlutil.Mapping()
	yamlutil.AddScalar(node, "apiVersion", "backstage.io/v1alpha1")
	yamlutil.AddScalar(node, "kind", "Component")

	metadata := yamlutil.Mapping()
	yamlutil.AddScalar(metadata, "name", in.ServiceName)
	annotations := yamlutil.Mapping()
	yamlutil.AddScalar(annotations, "backstage.io/source-location", "url:"+in.RepoTreeURL)
	yamlutil.AddMapping(metadata, "annotations", annotations)
	yamlutil.AddMapping(node, "metadata", metadata)

	spec := yamlutil.Mapping()
	yamlutil.AddScalar(spec, "type", "service")
	yamlutil.AddScalar(spec, "lifecycle", "experimental")
	yamlutil.AddScalar(spec, "owner", in.Owner)

	var providesApis []string
	if in.HasOpenAPI {
		providesApis = append(providesApis, in.ServiceName+"-rest")
	}
	if in.HasAsyncAPI {
		providesApis = append(providesApis, in.ServiceName+"-events")
	}
	providesNode, _ := yamlutil.AnyToNode(providesApis)
	yamlutil.AddMapping(spec, "providesApis", providesNode)

	consumesNode, _ := yamlutil.AnyToNode([]string{})
	yamlutil.AddMapping(spec, "consumesApis", consumesNode)

	yamlutil.AddMapping(node, "spec", spec)
	return node
}

func buildOpenAPIEntity(in Input) *yaml.Node {
	node := yamlutil.Mapping()
	yamlutil.AddScalar(node, "apiVersion", "backstage.io/v1alpha1")
	yamlutil.AddScalar(node, "kind", "API")

	metadata := yamlutil.Mapping()
	yamlutil.AddScalar(metadata, "name", in.ServiceName+"-rest")
	yamlutil.AddMapping(node, "metadata", metadata)

	spec := yamlutil.Mapping()
	yamlutil.AddScalar(spec, "type", "openapi")
	yamlutil.AddScalar(spec, "lifecycle", "experimental")
	yamlutil.AddScalar(spec, "owner", in.Owner)

	definition := yamlutil.Mapping()
	yamlutil.AddScalar(definition, "$text", "./openapi.yaml")
	yamlutil.AddMapping(spec, "definition", definition)

	yamlutil.AddMapping(node, "spec", spec)
	return node
}

func buildAsyncAPIEntity(in Input) *yaml.Node {
	node := yamlutil.Mapping()
	yamlutil.AddScalar(node, "apiVersion", "backstage.io/v1alpha1")
	yamlutil.AddScalar(node, "kind", "API")

	metadata := yamlutil.Mapping()
	yamlutil.AddScalar(metadata, "name", in.ServiceName+"-events")

	if len(in.ExposedNames) > 0 {
		annotations := yamlutil.Mapping()
		yamlutil.AddScalar(annotations, "bookinfo.io/exposed-event-names", strings.Join(in.ExposedNames, ","))
		yamlutil.AddMapping(metadata, "annotations", annotations)
	}

	yamlutil.AddMapping(node, "metadata", metadata)

	spec := yamlutil.Mapping()
	yamlutil.AddScalar(spec, "type", "asyncapi")
	yamlutil.AddScalar(spec, "lifecycle", "experimental")
	yamlutil.AddScalar(spec, "owner", in.Owner)

	definition := yamlutil.Mapping()
	yamlutil.AddScalar(definition, "$text", "./asyncapi.yaml")
	yamlutil.AddMapping(spec, "definition", definition)

	yamlutil.AddMapping(node, "spec", spec)
	return node
}
