apiVersion: v1
kind: ConfigMap
metadata:
  name: productpage
data:
  LOG_LEVEL: "debug"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy-metrics-traces.observability.svc.cluster.local:4317"
  DETAILS_SERVICE_URL: "http://gateway.envoy-gateway-system.svc.cluster.local"
  REVIEWS_SERVICE_URL: "http://gateway.envoy-gateway-system.svc.cluster.local"
  RATINGS_SERVICE_URL: "http://gateway.envoy-gateway-system.svc.cluster.local"
