apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - hpa.yaml

patches:
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: productpage

configMapGenerator:
  - name: productpage
    behavior: merge
    literals:
      - LOG_LEVEL=warn
