apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    role: read
spec:
  replicas: 1
  template:
    metadata:
      labels:
        role: read
    spec:
      containers:
        - name: ratings
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits: {}
