apiVersion: v1
kind: Service
metadata:
  name: rating-submitted-eventsource-svc
  namespace: bookinfo
spec:
  selector:
    eventsource-name: rating-submitted
  ports:
    - port: 12002
      targetPort: 12002
