apiVersion: v1
kind: Service
metadata:
  name: ratings-write
  namespace: bookinfo
  labels:
    app: ratings
    role: write
    part-of: event-driven-bookinfo
spec:
  type: ClusterIP
  selector:
    app: ratings
    role: write
  ports:
    - name: http
      port: 80
      targetPort: 8080
