apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: review-deleted
spec:
  eventBusName: kafka
  webhook:
    review-deleted:
      port: "12003"
      endpoint: /review-deleted
      method: DELETE
