apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - eventsource.yaml
  - eventsource-delete.yaml
  - sensor.yaml

commonLabels:
  app: reviews
  part-of: event-driven-bookinfo
