apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cronjob.yaml

configMapGenerator:
  - name: k6-bookinfo-traffic
    options:
      disableNameSuffixHash: true
    files:
      - bookinfo-traffic.js=../../../test/k6/bookinfo-traffic.js
