apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: productpage
  namespace: bookinfo
spec:
  parentRefs:
    - name: default-gw
      namespace: platform
      sectionName: web
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: productpage
          port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: book-added-webhook
  namespace: bookinfo
spec:
  parentRefs:
    - name: default-gw
      namespace: platform
      sectionName: webhooks
  rules:
    - matches:
        - path:
            type: Exact
            value: /v1/book-added
      backendRefs:
        - name: book-added-eventsource-svc
          port: 12000
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: review-submitted-webhook
  namespace: bookinfo
spec:
  parentRefs:
    - name: default-gw
      namespace: platform
      sectionName: webhooks
  rules:
    - matches:
        - path:
            type: Exact
            value: /v1/review-submitted
      backendRefs:
        - name: review-submitted-eventsource-svc
          port: 12001
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: rating-submitted-webhook
  namespace: bookinfo
spec:
  parentRefs:
    - name: default-gw
      namespace: platform
      sectionName: webhooks
  rules:
    - matches:
        - path:
            type: Exact
            value: /v1/rating-submitted
      backendRefs:
        - name: rating-submitted-eventsource-svc
          port: 12002
