# deploy/ingestion/values-local-kafka.yaml
serviceName: ingestion
fullnameOverride: ingestion
image:
  repository: event-driven-bookinfo/ingestion
  tag: local

config:
  LOG_LEVEL: "debug"
  EVENT_BACKEND: "kafka"
  POLL_INTERVAL: "5m"
  SEARCH_QUERIES: "programming,golang,kubernetes,python,devops"
  MAX_RESULTS_PER_QUERY: "10"

events:
  bus:
    type: kafka
  kafka:
    broker: "bookinfo-kafka-kafka-bootstrap.platform.svc.cluster.local:9092"

observability:
  otelEndpoint: "http://alloy-metrics-traces.observability.svc.cluster.local:4317"
  pyroscopeAddress: "http://pyroscope.observability.svc.cluster.local:4040"
