apiVersion: v1
kind: Service
metadata:
  name: book-added-eventsource-svc
  namespace: bookinfo
spec:
  selector:
    eventsource-name: book-added
  ports:
    - port: 12000
      targetPort: 12000
---
apiVersion: v1
kind: Service
metadata:
  name: review-submitted-eventsource-svc
  namespace: bookinfo
spec:
  selector:
    eventsource-name: review-submitted
  ports:
    - port: 12001
      targetPort: 12001
---
apiVersion: v1
kind: Service
metadata:
  name: rating-submitted-eventsource-svc
  namespace: bookinfo
spec:
  selector:
    eventsource-name: rating-submitted
  ports:
    - port: 12002
      targetPort: 12002
