apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bookinfo

resources:
  - eventbus.yaml
  - eventsource-services.yaml
  - ../../eventsources/book-added.yaml
  - ../../eventsources/review-submitted.yaml
  - ../../eventsources/rating-submitted.yaml
  - sensors/book-added-sensor.yaml
  - sensors/review-submitted-sensor.yaml
  - sensors/rating-submitted-sensor.yaml
