package service_test

import (
	"context"
	"errors"
	"testing"
	"time"

	"github.com/kaio6fellipe/event-driven-bookinfo/services/dlqueue/internal/adapter/outbound/memory"
	"github.com/kaio6fellipe/event-driven-bookinfo/services/dlqueue/internal/core/domain"
	"github.com/kaio6fellipe/event-driven-bookinfo/services/dlqueue/internal/core/port"
	"github.com/kaio6fellipe/event-driven-bookinfo/services/dlqueue/internal/core/service"
)

type fakeReplayClient struct {
	calls []replayCall
	err   error
}

type replayCall struct {
	url     string
	payload []byte
	headers map[string][]string
}

func (f *fakeReplayClient) Replay(_ context.Context, url string, payload []byte, headers map[string][]string) error {
	f.calls = append(f.calls, replayCall{url, payload, headers})
	return f.err
}

func newParams(eventID string) port.IngestEventParams {
	return port.IngestEventParams{
		EventID:         eventID,
		EventType:       "webhook",
		EventSource:     "review-submitted",
		EventSubject:    "review-submitted",
		SensorName:      "review-submitted-sensor",
		FailedTrigger:   "create-review",
		EventSourceURL:  "http://esvc:12001/review-submitted",
		Namespace:       "bookinfo",
		OriginalPayload: []byte(`{"product_id":"p1"}`),
		OriginalHeaders: map[string][]string{"traceparent": {"00-abc"}},
		DataContentType: "application/json",
		EventTimestamp:  time.Now(),
	}
}

func TestIngest_NewEvent(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	svc := service.NewDLQService(repo, &fakeReplayClient{}, 3)

	e, err := svc.IngestEvent(ctx, newParams("evt-1"))
	if err != nil {
		t.Fatalf("IngestEvent err = %v", err)
	}
	if e.Status != domain.StatusPending {
		t.Errorf("status = %v, want pending", e.Status)
	}
	if e.RetryCount != 0 {
		t.Errorf("retry_count = %d, want 0", e.RetryCount)
	}
}

func TestIngest_Duplicate_IncrementsRetry(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	svc := service.NewDLQService(repo, &fakeReplayClient{}, 3)

	// First ingest.
	e1, _ := svc.IngestEvent(ctx, newParams("evt-1"))
	// Simulate that it was replayed.
	_ = e1.Replay()
	_ = repo.Update(ctx, e1)

	// Same payload+sensor+trigger arrives again (new event_id generated by Argo).
	params := newParams("evt-2-different-envelope-id")
	e2, err := svc.IngestEvent(ctx, params)
	if err != nil {
		t.Fatalf("IngestEvent err = %v", err)
	}
	if e2.ID != e1.ID {
		t.Errorf("expected same DLQ ID after dedup, got %q (orig %q)", e2.ID, e1.ID)
	}
	if e2.RetryCount != 1 {
		t.Errorf("retry_count = %d, want 1", e2.RetryCount)
	}
	if e2.Status != domain.StatusPending {
		t.Errorf("status = %v, want pending", e2.Status)
	}
}

func TestReplay_HappyPath(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	client := &fakeReplayClient{}
	svc := service.NewDLQService(repo, client, 3)

	e, _ := svc.IngestEvent(ctx, newParams("evt-1"))
	got, err := svc.ReplayEvent(ctx, e.ID)
	if err != nil {
		t.Fatalf("ReplayEvent err = %v", err)
	}
	if got.Status != domain.StatusReplayed {
		t.Errorf("status = %v, want replayed", got.Status)
	}
	if len(client.calls) != 1 {
		t.Fatalf("replay client calls = %d, want 1", len(client.calls))
	}
	if client.calls[0].url != "http://esvc:12001/review-submitted" {
		t.Errorf("url = %q, want original eventsource_url", client.calls[0].url)
	}
}

func TestResolve(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	svc := service.NewDLQService(repo, &fakeReplayClient{}, 3)

	e, _ := svc.IngestEvent(ctx, newParams("evt-1"))
	_, _ = svc.ReplayEvent(ctx, e.ID)
	got, err := svc.ResolveEvent(ctx, e.ID, "ratings-service")
	if err != nil {
		t.Fatalf("ResolveEvent err = %v", err)
	}
	if got.Status != domain.StatusResolved {
		t.Errorf("status = %v, want resolved", got.Status)
	}
	if got.ResolvedBy != "ratings-service" {
		t.Errorf("resolved_by = %q", got.ResolvedBy)
	}
}

func TestResetPoisoned(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	svc := service.NewDLQService(repo, &fakeReplayClient{}, 1) // max=1 → first ReIngest poisons

	e, _ := svc.IngestEvent(ctx, newParams("evt-1"))
	_, _ = svc.ReplayEvent(ctx, e.ID)
	// Replay fails, same payload comes back:
	e2, _ := svc.IngestEvent(ctx, newParams("evt-2"))
	if e2.Status != domain.StatusPoisoned {
		t.Fatalf("expected poisoned after re-ingest at max, got %v", e2.Status)
	}

	got, err := svc.ResetPoisoned(ctx, e2.ID)
	if err != nil {
		t.Fatalf("ResetPoisoned err = %v", err)
	}
	if got.Status != domain.StatusPending {
		t.Errorf("status = %v, want pending", got.Status)
	}
	if got.RetryCount != 0 {
		t.Errorf("retry_count = %d, want 0", got.RetryCount)
	}
}

func TestBatchReplay(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	client := &fakeReplayClient{}
	svc := service.NewDLQService(repo, client, 3)

	// 3 distinct pending events — distinct sensor OR trigger OR payload to avoid dedup.
	for i := 0; i < 3; i++ {
		p := newParams("evt-" + string(rune('a'+i)))
		p.SensorName = "sensor-" + string(rune('a'+i))
		p.OriginalPayload = []byte(`{"i":"` + string(rune('0'+i)) + `"}`)
		_, _ = svc.IngestEvent(ctx, p)
	}

	n, err := svc.BatchReplay(ctx, port.BatchFilter{Status: string(domain.StatusPending), Limit: 10})
	if err != nil {
		t.Fatalf("BatchReplay err = %v", err)
	}
	if n != 3 {
		t.Errorf("replayed count = %d, want 3", n)
	}
	if len(client.calls) != 3 {
		t.Errorf("replay client calls = %d, want 3", len(client.calls))
	}
}

func TestBatchResolve(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	svc := service.NewDLQService(repo, &fakeReplayClient{}, 3)

	var ids []string
	for i := 0; i < 3; i++ {
		p := newParams("evt-" + string(rune('a'+i)))
		p.SensorName = "sensor-" + string(rune('a'+i))
		p.OriginalPayload = []byte(`{"i":"` + string(rune('0'+i)) + `"}`)
		e, _ := svc.IngestEvent(ctx, p)
		_, _ = svc.ReplayEvent(ctx, e.ID)
		ids = append(ids, e.ID)
	}

	n, err := svc.BatchResolve(ctx, ids, "batch-op")
	if err != nil {
		t.Fatalf("BatchResolve err = %v", err)
	}
	if n != 3 {
		t.Errorf("resolved count = %d, want 3", n)
	}
}

func TestGetEvent(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	svc := service.NewDLQService(repo, &fakeReplayClient{}, 3)

	saved, _ := svc.IngestEvent(ctx, newParams("evt-1"))

	got, err := svc.GetEvent(ctx, saved.ID)
	if err != nil {
		t.Fatalf("GetEvent err = %v", err)
	}
	if got.ID != saved.ID {
		t.Errorf("id = %q, want %q", got.ID, saved.ID)
	}

	_, err = svc.GetEvent(ctx, "missing")
	if !errors.Is(err, domain.ErrNotFound) {
		t.Errorf("err = %v, want ErrNotFound", err)
	}
}

func TestListEvents(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	svc := service.NewDLQService(repo, &fakeReplayClient{}, 3)

	p1 := newParams("evt-1")
	p2 := newParams("evt-2")
	p2.SensorName = "other-sensor"
	p2.OriginalPayload = []byte(`{"other":true}`)
	_, _ = svc.IngestEvent(ctx, p1)
	_, _ = svc.IngestEvent(ctx, p2)

	items, total, err := svc.ListEvents(ctx, port.ListFilter{Limit: 10})
	if err != nil {
		t.Fatalf("ListEvents err = %v", err)
	}
	if total != 2 {
		t.Errorf("total = %d, want 2", total)
	}
	if len(items) != 2 {
		t.Errorf("items len = %d, want 2", len(items))
	}

	_, total, _ = svc.ListEvents(ctx, port.ListFilter{Status: string(domain.StatusResolved), Limit: 10})
	if total != 0 {
		t.Errorf("resolved total = %d, want 0", total)
	}
}

func TestReplay_ReplayerError(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	client := &fakeReplayClient{err: errors.New("transport failure")}
	svc := service.NewDLQService(repo, client, 3)

	e, _ := svc.IngestEvent(ctx, newParams("evt-1"))

	_, err := svc.ReplayEvent(ctx, e.ID)
	if err == nil {
		t.Fatal("expected replay error, got nil")
	}

	// Rollback contract: transport failure leaves status as pending.
	got, err := svc.GetEvent(ctx, e.ID)
	if err != nil {
		t.Fatalf("GetEvent err = %v", err)
	}
	if got.Status != domain.StatusPending {
		t.Errorf("status = %v, want pending (replay should not persist on transport error)", got.Status)
	}
	if got.LastReplayedAt != nil {
		t.Errorf("expected LastReplayedAt to remain nil after failed replay")
	}
}

func TestReplayEvent_NotFound(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	svc := service.NewDLQService(repo, &fakeReplayClient{}, 3)

	_, err := svc.ReplayEvent(ctx, "no-such-id")
	if !errors.Is(err, domain.ErrNotFound) {
		t.Errorf("err = %v, want ErrNotFound", err)
	}
}

func TestReplayEvent_InvalidTransition(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	svc := service.NewDLQService(repo, &fakeReplayClient{}, 3)

	e, _ := svc.IngestEvent(ctx, newParams("evt-1"))
	// Replay once to move to replayed state.
	_, _ = svc.ReplayEvent(ctx, e.ID)
	// Second replay from replayed state should fail.
	_, err := svc.ReplayEvent(ctx, e.ID)
	if !errors.Is(err, domain.ErrInvalidTransition) {
		t.Errorf("err = %v, want ErrInvalidTransition", err)
	}
}

func TestResolveEvent_NotFound(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	svc := service.NewDLQService(repo, &fakeReplayClient{}, 3)

	_, err := svc.ResolveEvent(ctx, "no-such-id", "operator")
	if !errors.Is(err, domain.ErrNotFound) {
		t.Errorf("err = %v, want ErrNotFound", err)
	}
}

func TestResetPoisoned_NotFound(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	svc := service.NewDLQService(repo, &fakeReplayClient{}, 3)

	_, err := svc.ResetPoisoned(ctx, "no-such-id")
	if !errors.Is(err, domain.ErrNotFound) {
		t.Errorf("err = %v, want ErrNotFound", err)
	}
}

func TestBatchReplay_TransportError(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	client := &fakeReplayClient{err: errors.New("transport failure")}
	svc := service.NewDLQService(repo, client, 3)

	p := newParams("evt-1")
	_, _ = svc.IngestEvent(ctx, p)

	n, err := svc.BatchReplay(ctx, port.BatchFilter{Status: string(domain.StatusPending), Limit: 10})
	if err == nil {
		t.Fatal("expected error from BatchReplay, got nil")
	}
	if n != 0 {
		t.Errorf("replayed count = %d, want 0", n)
	}
}

func TestBatchResolve_AlreadyResolved(t *testing.T) {
	ctx := context.Background()
	repo := memory.NewDLQRepository()
	svc := service.NewDLQService(repo, &fakeReplayClient{}, 3)

	e, _ := svc.IngestEvent(ctx, newParams("evt-1"))
	_, _ = svc.ResolveEvent(ctx, e.ID, "first")

	// Resolving an already-resolved event must return an error.
	n, err := svc.BatchResolve(ctx, []string{e.ID}, "second")
	if err == nil {
		t.Fatal("expected error resolving already-resolved event, got nil")
	}
	if n != 0 {
		t.Errorf("resolved count = %d, want 0", n)
	}
}
